### ISSUE TITLE
Support for container image build

### ISSUE THREAD

**Issue by priyanknarvekar** [quarkiverse/quarkus-quinoa#156]
Container image for quinoaA app build using the quarkus-container-image-jib extension, fails to start 
just running the application from the target directory runs fine , 

but when a container images is build from the Quinoa app project using the jib extension, the container logs throws exception/error:
```
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
--
Tue, Jul 26 2022 6:37:40 pm | 2022-07-26 22:37:40,541 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider
Tue, Jul 26 2022 6:37:40 pm |  
Tue, Jul 26 2022 6:37:40 pm | Exception in thread "main" java.nio.file.NoSuchFileException: /home/jboss/lib/deployment/deployment-class-path.dat
Tue, Jul 26 2022 6:37:40 pm | at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
Tue, Jul 26 2022 6:37:40 pm | at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
Tue, Jul 26 2022 6:37:40 pm | at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
Tue, Jul 26 2022 6:37:40 pm | at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
Tue, Jul 26 2022 6:37:40 pm | at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
Tue, Jul 26 2022 6:37:40 pm | at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
Tue, Jul 26 2022 6:37:40 pm | at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
Tue, Jul 26 2022 6:37:40 pm | at java.base/java.nio.file.Files.newInputStream(Files.java:156)
Tue, Jul 26 2022 6:37:40 pm | at io.quarkus.bootstrap.runner.DevModeMediator.doStart(DevModeMediator.java:39)
Tue, Jul 26 2022 6:37:40 pm | at io.quarkus.bootstrap.runner.DevModeMediator.doDevMode(DevModeMediator.java:29)
Tue, Jul 26 2022 6:37:40 pm | at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:45)
Tue, Jul 26 2022 6:37:40 pm | at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
```

**Comment by ia3andy** [comment]
This seems related: https://github.com/quarkusio/quarkus/issues/12601

**Comment by geoand** [comment]
I would need to know what the flow is that results in this since there are multiple pieces that are in play
