### ISSUE TITLE
Quinoa PackageManager not working on own Gitlab Ci/Cd

### ISSUE THREAD

**Issue by Codegiven** [quarkiverse/quarkus-quinoa#160]
I am trying to use Gitlab runner to build a Quarkus/Quinoa app.
The setup is Java 11 with Maven and the frontend uses Angular 14.1.1

Running the Quarkus server in dev mode works really nice, as well as running mvnw verify locally.
The issue only exits on the GitLab runner.

**Project structure**
```
myApp 
│
└───frontend
│   │
│   └───myApp
│   
└───src
     │
     └───main
     │  
     └───test
```
**Pipeline Step**
```
run-test:
  stage: test
  image: myOwnQuinoaImage:latest
  script:
    - ./mvnw verify
```

**myOwnQuinoaImage:latest**
```
FROM alpine:3.15.5

RUN apk add openjdk11
RUN apk add maven
RUN apk add nodejs
RUN apk add npm
```

**pom.xml**
```
...    
<dependency>
  <groupId>io.quarkiverse.quinoa</groupId>
  <artifactId>quarkus-quinoa</artifactId>
  <version>1.1.2</version>
</dependency>
...
```

**application.properties**
```
quarkus.quinoa.ui-dir=./frontend/myApp
quarkus.quinoa.build-dir=dist/myApp
quarkus.quinoa.enable-spa-routing=true
quarkus.quinoa.force-install=true
...
```

**Exception log taken from the pipeline**
```
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm ERR! code E401
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm ERR! Incorrect or missing password.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm ERR! If you were trying to login, change your password, create an
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm ERR! authentication token or enable two-factor authentication then
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm ERR! that means you likely typed your password in incorrectly.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm ERR! Please try again, or recover your password at:
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm ERR!     https://www.npmjs.com/forgot
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm ERR! 
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm ERR! If you were doing some other operation then your saved credentials are
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm ERR! probably out of date. To correct this please try logging in again with:
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm ERR!     npm login
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] 
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm ERR! A complete log of this run can be found in:
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm ERR!     /root/.npm/_logs/2022-08-09T09_39_19_934Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:19 min
[INFO] Finished at: 2022-08-09T09:39:20Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.10.2.Final:build (default) on project myProject: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkiverse.quinoa.deployment.QuinoaProcessor#prepareQuinoaDirectory threw an exception: java.lang.RuntimeException: Error in Quinoa while running package manager install command: npm install
[ERROR] 	at io.quarkiverse.quinoa.deployment.packagemanager.PackageManager.install(PackageManager.java:44)
[ERROR] 	at io.quarkiverse.quinoa.deployment.QuinoaProcessor.prepareQuinoaDirectory(QuinoaProcessor.java:100)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:944)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by ia3andy** [comment]
Have a look at this:
https://stackoverflow.com/questions/67114659/npm-err-code-e401-npm-err-incorrect-or-missing-password

It could be some .npmrc file, a private registry or a NodeJs version conflict.

**Comment by Codegiven** [comment]
> Have a look at this: https://stackoverflow.com/questions/67114659/npm-err-code-e401-npm-err-incorrect-or-missing-password
> 
> It could be some .npmrc file, a private registry or a NodeJs version conflict.

Removing the package-lock.json did the trick.

Thank you very much, for this fast response
