### ISSUE TITLE
Quarkus Angular - Port 4200 Live Coding is not Listening

### ISSUE THREAD

**Issue by jefrog1844** [quarkiverse/quarkus-quinoa#227]
Here are my configurations and the stack trace below.  If I run ng build, that works fine.  I can even run ng serve in my webui directory and angular starts that way as well.  Does anyone know a solution for the check timeout?

Thanks

Quarkus: 2.14.3
Angular 14.0.0
JDK 11

APPLICATION.PROPERTIES
quarkus.quinoa.build-dir=dist/webui
quarkus.quinoa.enable-spa-routing=true
quarkus.quinoa.dev-server.port=4200

PACKAGE.JSON
"start": "ng serve --host 0.0.0.0 --no-live-reload",

MacBook-Air:dfmea jeffrogers$ quarkus dev
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< com.mfmea:dfmea >---------------------------
[INFO] Building dfmea 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:2.14.3.Final:dev (default-cli) @ dfmea ---
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources @ dfmea
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.14.3.Final:generate-code @ dfmea
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile @ dfmea
[INFO] Nothing to compile - all classes are up to date
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources @ dfmea
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/jeffrogers/JavaWorkspace/Github/dfmea/src/test/resources
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.14.3.Final:generate-code-tests @ dfmea
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile @ dfmea
[INFO] No sources to compile
Listening for transport dt_socket at address: 5005
2023-01-04 19:07:38,274 INFO  [io.qua.qui.dep.pac.PackageManager] (build-10) Running Quinoa package manager live coding as a dev service: npm start

> webui@0.0.0 start
> ng serve --host 0.0.0.0

Warning: This is a simple server for use in testing or debugging Angular applications
locally. It hasn't been reviewed for security issues.

Binding this server to an open connection can result in compromising your application or
computer. Using a different host than the one passed to the "--host" flag might result in
websocket connection issues. You might need to use "--disable-host-check" if that's the
case.
- Generating browser application bundles (phase: setup)...
2023-01-04 19:08:15,925 INFO  [io.qua.qui.dep.pac.PackageManager] (build-10) Stopping Quinoa package manager live coding as a dev service.
2023-01-04 19:08:16,066 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-01-04 19:08:16,971 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.quinoa.deployment.ForwardedDevProcessor#prepareDevService threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Quinoa package manager live coding port 4200 is still not listening after the checkTimeout.
	at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Quinoa package manager live coding port 4200 is still not listening after the checkTimeout.
	at io.quarkiverse.quinoa.deployment.packagemanager.PackageManager.dev(PackageManager.java:113)
	at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:122)
	... 11 more

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:86)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:59)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.quinoa.deployment.ForwardedDevProcessor#prepareDevService threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Quinoa package manager live coding port 4200 is still not listening after the checkTimeout.
	at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Quinoa package manager live coding port 4200 is still not listening after the checkTimeout.
	at io.quarkiverse.quinoa.deployment.packagemanager.PackageManager.dev(PackageManager.java:113)
	at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:122)
	... 11 more

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Quinoa package manager live coding port 4200 is still not listening after the checkTimeout.
	at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Quinoa package manager live coding port 4200 is still not listening after the checkTimeout.
	at io.quarkiverse.quinoa.deployment.packagemanager.PackageManager.dev(PackageManager.java:113)
	at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:122)
	... 11 more

**Comment by jefrog1844** [comment]
I created another quarkus-angular-quinoa app, and ran it fine.  Then came back and restarted the original app I had the timeout issue with and it started.  I've checked ports and made sure nothing was on 4200. Not sure why I experience this random behavior with timeout.

**Comment by ia3andy** [comment]
@jefrog1844 Have you tried to increase the timeout? https://quarkiverse.github.io/quarkiverse-docs/quarkus-quinoa/dev/index.html#quarkus-quinoa_quarkus.quinoa.dev-server.check-timeout

**Comment by jefrog1844** [comment]
I did not know about that setting, my bad because I didn't review all of them.  Thanks for the advice.  I just timed my app from the time I enter "quarkus dev" until I see "Quinoa is forwarding unhandled requests to port: 4200" and that was about 41 seconds so yes, 30000ms may just be borderline.  I've increased it now and will monitor if the issue goes away.

**Comment by jefrog1844** [comment]
FYI, I wanted to see how sensitive this timeout setting is for generating the checkTimeout error.  I set it to 3000 and the checkTimeout happens every time I try to start the app, so I'm pretty sure this is the issue.  I set it back to 60000 and it starts up.  I'll try to report back in a few days or so as to whether or not I see the error anymore.

**Comment by ia3andy** [comment]
Awesome, I am glad it works now :)

I am closing, feel free to re-open if the problem is different.

**Comment by jefrog1844** [comment]
Sounds good.  So far with the updating setting I have no timeout issue.
