### ISSUE TITLE
Quinoa dev server forwards to ipv6 loopback address, instead of ipv4

### ISSUE THREAD

**Issue by baalimago** [quarkiverse/quarkus-quinoa#266]
Hello!

I'm trying to embedd a vite vue frontend into my quarkus app. I've followed the steps here: https://quarkiverse.github.io/quarkiverse-docs/quarkus-quinoa/dev/#vite

While runing `quarkus dev` it starts up without issues. But when attempting to reach localhost:8080, I get this issue where Quinoa attempts to forward requests to the ipv6 loopback address, instead of ipv4:
```
$ quarkus dev
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< <redacted>:<redacted>>------------------------
[INFO] Building <redacted>1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:2.16.4.Final:dev (default-cli) @ <redacted>---
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources @ <redacted>
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.16.4.Final:generate-code @ <redacted>
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile @ <redacted>
[INFO] Nothing to compile - all classes are up to date
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources @ <redacted>
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/imago/Projects/<redacted>/src/test/resources
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.16.4.Final:generate-code-tests @ <redacted>
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile @ <redacted>
[INFO] Nothing to compile - all classes are up to date
Listening for transport dt_socket at address: 5005
2023-03-08 06:52:16,892 INFO  [com.git.eir.mav.plu.fro.lib.NodeInstaller] (build-10) Node v16.17.0 is already installed.
2023-03-08 06:52:18,601 INFO  [io.qua.qui.dep.ForwardedDevProcessor] (build-8) Quinoa package manager live coding is up and running on port: 5173 (in 1575ms)
2023-03-08 06:52:18,604 INFO  [io.qua.qui.dep.ForwardedDevProcessor] (build-13) Quinoa is forwarding unhandled requests to port: 5173
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-03-08 06:52:19,128 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.quinoa.dev-server.host" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo <- Here I "guessed" how I maybe could target the host
2023-03-08 06:52:19,449 INFO  [io.quarkus] (Quarkus Main Thread) <redacted>1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.16.4.Final) started in 3.298s. Listening on: http://0.0.0.0:8080
2023-03-08 06:52:19,450 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2023-03-08 06:52:19,450 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, quinoa, resteasy-reactive, smallrye-context-propagation, vertx]
2023-03-08 06:52:29,068 ERROR [io.qua.qui.QuinoaDevProxyHandler] (vert.x-eventloop-thread-2) Quinoa failed to forward request, see logs.: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /[0:0:0:0:0:0:0:1]:5173
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

My vue app is reachable on 127.0.0.1:5173 
```
$ curl "http://localhost:5173"   
<!DOCTYPE html>
<html lang="en">
  <head>
    <script type="module" src="/@vite/client"></script>

    <meta charset="UTF-8">
    <link rel="icon" href="/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vite App</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html
```

But it's not reachable on [::1]:5173
```
$ curl -6 "http://[::1]:5173"
curl: (7) Failed to connect to ::1 port 5173: Connection refused
```

So an alternative is to figure out how to make npm host ipv6 servers, but that's somewhat useless as this npm server only will be used for local debugging. I'd prefer if I could make Quinoa target the ipv4 address, or force it to enter "ipv4-mode" somehow. Is this possible?

Current environment is:
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
...
$ java --version
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
$ quarkus version
2.16.4.Final
```

Many thanks,

Imago

**Comment by ia3andy** [comment]
what is you use this:
```
  server: {
    port: 5173,
    host: '127.0.0.1',
    hmr: {
      port: 5173,
      host: '127.0.0.1',
    }
  }
  ```

**Comment by ia3andy** [comment]
this is what's used to forward the request, I don't understand why it would target the ipv6:
https://github.com/quarkiverse/quarkus-quinoa/blob/main/runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java#L69

You could try to to debug this line and see why you get a ipv6?

**Comment by baalimago** [comment]
Thanks for quick reply, I did as you asked:
![image](https://user-images.githubusercontent.com/21121209/223934424-434ad940-1c75-4924-b47b-f7c898110fe6.png)

It seems like the request itself is is ipv6. This got me suspicious, so (naturally) I did some curling:
```
$ curl -s http://localhost:8080
<!DOCTYPE html>
<html lang="en">
  <head>
    <script type="module" src="/@vite/client"></script>

    <meta charset="UTF-8">
    <link rel="icon" href="/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vite App</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
```
It's reachable from within wsl using ipv4, not reachable from inside wsl using ipv6:
```
$ curl "http://[::1]:8080"
Quinoa failed to forward request, see logs.%
```

So I think the issue is on my end somehow. Seems like my browsers only can reach WSL ipv6 loopback, not ipv4, and thus quarkus+quinoa interprets the request as an ipv6  one (and attempts to proxy it as such). 

I'll keep digging on my end to see why my browsers can't reach WSL ipv4 loopback

**Comment by baalimago** [comment]
> what is you use this:
> 
> ```
>   server: {
>     port: 5173,
>     host: '127.0.0.1',
>     hmr: {
>       port: 5173,
>       host: '127.0.0.1',
>     }
>   }
> ```


Where/how can I configure this? I'm very new to Quarkus and modern Java

**Comment by ia3andy** [comment]
> > what is you use this:
> > ```
> >   server: {
> >     port: 5173,
> >     host: '127.0.0.1',
> >     hmr: {
> >       port: 5173,
> >       host: '127.0.0.1',
> >     }
> >   }
> > ```
> 
> Where/how can I configure this? I'm very new to Quarkus and modern Java

This is in the vite config

**Comment by melloware** [comment]
@baalimago I am using WSL and it works fine I can hit the IP of Vite from my Windows host running my Quinoa Vite app.

I haven't seen any issues?

**Comment by ia3andy** [comment]
@baalimago any update on this issue?

**Comment by ia3andy** [comment]
Closing, feel free to re-open.

**Comment by ia3andy** [comment]
This is now fixed
