### ISSUE TITLE
NPE when webui folder is in the wrong place (misconfiguration)

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-quinoa#355]
### Describe the bug

I had my `webui` folder at the wrong level. Quinoa helpfully told me about the issue:

```
2023-05-18 11:59:26,432 WARN  [io.qua.qui.dep.QuinoaProcessor] (build-29) Quinoa directory not found 'quarkus.quinoa.ui-dir=src/main/webui' resolved to '/Users/holly/Code/demos/quarkus-workshops/quarkus-workshop-super-heroes/super-heroes/ui-super-heroes/src/main/webui'. It is recommended to remove the quarkus-quinoa extension if not used.
2023-05-18 11:59:26,434 WARN  [io.qua.qui.dep.QuinoaProcessor] (build-27) Quinoa directory not found 'quarkus.quinoa.ui-dir=src/main/webui' resolved to '/Users/holly/Code/demos/quarkus-workshops/quarkus-workshop-super-heroes/super-heroes/ui-super-heroes/src/main/webui'. It is recommended to remove the quarkus-quinoa extension if not used.
```

... but then went on to NPE, which made it harder to see the warning 

```
2023-05-18 11:59:26,565 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-05-18 11:59:26,817 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.quinoa.deployment.QuinoaProcessor#hotDeploymentWatchedFiles threw an exception: java.lang.NullPointerException: Cannot read field "uiDir" because "projectDirs" is null
Press [:at io.quarkiverse.quinoa.deployment.QuinoaProcessor.hotDeploymentWatchedFiles(QuinoaProcessor.java:230)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
```

Obviously, I should configure things correctly, but it'd be nice if the failure mode was less noisy and NPE-ish when I get it wrong. :) 

Is this likely to be a common issue? When people are trying to retrofit Quinoa to an existing application, it's seems likely that they might have things in the wrong place on the first attempt.

### Quinoa version

2.0.3

### Quarkus version

2.15.3

### Build / Runtime

Angular

### Package Manager

NPM

### Steps to reproduce the behavior

Create a Quinoa project, and then move `webui` somewhere else or rename it.

### Expected behavior

I think it would be better to have the warning, and then to have a null check to prevent the NPE.

**Comment by melloware** [comment]
I will fix this. Thanks for reporting!

**Comment by melloware** [comment]
PR Submitted

**Comment by ia3andy** [comment]
thanks @melloware
