### ISSUE TITLE
Error while yarn package manager install with --frozen-lockfile argument

### ISSUE THREAD

**Issue by shivam-sharma7** [quarkiverse/quarkus-quinoa#506]
### Describe the bug

```
[ERROR] Errors:
[ERROR]   QuinoaFrozenLockfileConfigTest » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.quinoa.deployment.QuinoaProcessor#prepareQuinoaDirectory threw an exception: java.lang.RuntimeException: Error in Quinoa while running package manager install command: yarn.cmd install --frozen-lockfile
        at io.quarkiverse.quinoa.deployment.packagemanager.PackageManager.install(PackageManager.java:53)
        at io.quarkiverse.quinoa.deployment.QuinoaProcessor.prepareQuinoaDirectory(QuinoaProcessor.java:106)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

[ERROR]   QuinoaPackageManagerSetYarnConfigTest » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.quinoa.deployment.QuinoaProcessor#prepareQuinoaDirectory threw an exception: java.lang.RuntimeException: Error in Quinoa while running package manager install command: yarn.cmd install
        at io.quarkiverse.quinoa.deployment.packagemanager.PackageManager.install(PackageManager.java:53)
        at io.quarkiverse.quinoa.deployment.QuinoaProcessor.prepareQuinoaDirectory(QuinoaProcessor.java:106)
        at jdk.internal.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

[INFO]
[ERROR] Tests run: 24, Failures: 0, Errors: 2, Skipped: 0
```
cc @melloware 

### Quinoa version

2.1.0

### Quarkus version

3.3.x

### Build / Runtime

Other

### Package Manager

None

### Steps to reproduce the behavior

NA

### Expected behavior

NA

**Comment by ia3andy** [comment]
could you retry with quinoa 2.2.0.CR3 or give the full logs so we can see why the command failed (closing until you reproduce).

**Comment by melloware** [comment]
OK still getting this running `mvn clean install` from current `main`.

```
[ERROR]   QuinoaCIConfigTest » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.quinoa.deployment.QuinoaProcessor#install threw an exception: java.lang.RuntimeException: Error in Quinoa while running package manager ci command: yarn.cmd install --frozen-lockfile
        at io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner.ci(PackageManagerRunner.java:63)
        at io.quarkiverse.quinoa.deployment.QuinoaProcessor.install(QuinoaProcessor.java:139)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

[ERROR]   QuinoaPackageManagerSetYarnConfigTest » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.quinoa.deployment.QuinoaProcessor#install threw an exception: java.lang.RuntimeException: Error in Quinoa while running package manager install command: yarn.cmd install
        at io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner.install(PackageManagerRunner.java:72)
        at io.quarkiverse.quinoa.deployment.QuinoaProcessor.install(QuinoaProcessor.java:141)
        at jdk.internal.reflect.GeneratedMethodAccessor169.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

[INFO]
[ERROR] Tests run: 34, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by melloware** [comment]
@ia3andy I attached my entire run log here if you want to see:
[out.txt](https://github.com/quarkiverse/quarkus-quinoa/files/12768042/out.txt)

**Comment by ia3andy** [comment]
@melloware it's not related to the frozen lock file, have a look to this:
2023-09-29 11:10:01,827 INFO  [io.qua.qui.dep.pac.PackageManagerRunner] (build-28) â¤ YN0009: â quinoa-app@workspace:. couldn't be built successfully (exit code 1, logs can be found here: C:\Users\MELLOW~1\AppData\Local\Temp\xfs-de16ff11\build.log)
2023-09-29 11:10:01,827 INFO  [io.qua.qui.dep.pac.PackageManagerRunner] (build-28) â¤ YN0000: â Completed
2023-09-29 11:10:01,828 INFO  [io.qua.qui.dep.pac.PackageManagerRunner] (build-28) â¤ YN0000: Failed with errors in 1s 937ms

**Comment by ia3andy** [comment]
Could you try to reproduce the same install from the webui directory and call the install manually, see if you can reproduce

**Comment by melloware** [comment]
good idea let me try that.

**Comment by melloware** [comment]
OK the underlying YARN error is this `Error: ENOENT: no such file or directory, open 'C:\dev\quarkus\quarkus-quinoa\deployment\target\test-webui-package-manager-set-yarn\node_modules\installed'`

**Comment by melloware** [comment]
Found the answer: https://github.com/yarnpkg/yarn/issues/5500

https://github.com/yarnpkg/yarn/issues/5500#issuecomment-1221456246

Explained by this poster: https://github.com/yarnpkg/yarn/issues/5500#issuecomment-1409763038

**Comment by melloware** [comment]
got past that now getting this: ` YN0050: The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache instead`
