### ISSUE TITLE
Angular no longer works with 2.2.0.CR1 (pnpm)

### ISSUE THREAD

**Issue by ThoSap** [quarkiverse/quarkus-quinoa#520]
### Describe the bug

My start script is
```json
"start": "ng serve"
```
and I'm using Angular `16.2.6`.

I get the following error if I start the Quarkus dev server:
```java
2023-09-25T22:31:45.272Z INFO  [FrameworkType] (build-10) Quinoa detected 'ANGULAR' framework from package.json file.
2023-09-25T22:31:46.108Z INFO  [PackageManagerRunner] (build-11) Running Quinoa package manager live coding as a dev service: pnpm run start -- --disable-host-check
> fss-web@0.1.0 start C:\Users\ThoSap\IdeaProjects\fss-web\src\main\webui
> ng serve "--" "--disable-host-check"
Option '--' has been specified multiple times. The value '--disable-host-check' will be used.
Error: Schema validation failed with the following errors:
  Data path "" must NOT have additional properties().
?ELIFECYCLE? Command failed with exit code 1.
2023-09-25 22:32:48,506 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-09-25 22:32:48,801 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.quinoa.deployment.ForwardedDevProcessor#prepareDevService threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Quinoa package manager live coding port 4200 is still not listening after the checkTimeout.
	at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:162)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Quinoa package manager live coding port 4200 is still not listening after the checkTimeout.
	at io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner.dev(PackageManagerRunner.java:161)
	at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:136)
	... 11 more

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:336)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:253)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:113)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:438)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:56)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.quinoa.deployment.ForwardedDevProcessor#prepareDevService threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Quinoa package manager live coding port 4200 is still not listening after the checkTimeout.
	at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:162)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Quinoa package manager live coding port 4200 is still not listening after the checkTimeout.
	at io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner.dev(PackageManagerRunner.java:161)
	at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:136)
	... 11 more

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:332)
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Quinoa package manager live coding port 4200 is still not listening after the checkTimeout.
	at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:162)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Quinoa package manager live coding port 4200 is still not listening after the checkTimeout.
	at io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner.dev(PackageManagerRunner.java:161)
	at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:136)
	... 11 more
```

### Quinoa version

2.2.0.CR1

### Quarkus version

3.4.1

### Build / Runtime

Angular

### Package Manager

PNPM

### Steps to reproduce the behavior

Modify the package.json start script as follows:
```json
"start": "ng serve"
```

### Expected behavior

Start the Quarkus dev server, and the Angular dev server

**Comment by melloware** [comment]
Can you compare you project with this one?  https://github.com/ia3andy/quinoa-angular-root-path

This is a fully working Angular app with the latest Quinoa.

**Comment by ThoSap** [comment]
@melloware of course.

I checked the dependency versions of the `pom.xml` of this example project and compared them with my `build.gradle`, and noticed that the example project is using Quinoa `2.1.0`.
https://github.com/ia3andy/quinoa-angular-root-path/blob/f93076979dacb07f4d10558041c6f99a2091cf6b/pom.xml#L31-L35

If I downgrade from `2.2.0.CR1` to `2.1.0` starting `./gradlew quarkusDev` works just fine.

**Comment by melloware** [comment]
OK assigned to @ia3andy to investigate.

**Comment by ia3andy** [comment]
Ok, it seems pnpm is not happy with the `--` added by Quinoa, I will have a look on how to best fix this. Thanks so much for creating this issue and trying the CR1, this prevent the final version from being buggy :)

**Comment by ia3andy** [comment]
I will soon have a fix...

**Comment by ThoSap** [comment]
Tested Quinoa `2.2.0.CR2` with **PNPM**, works now!.
Thank you so much!
