### ISSUE TITLE
NextJS - Failed to start Quarkus

### ISSUE THREAD

**Issue by l2c0r3** [quarkiverse/quarkus-quinoa#603]
### Describe the bug

When I create a fresh NextJS application with Quarkus, the DEV mode works without any problems.
The QuarkusTests also work, but I have the following errors with the QuarkusIntegrationTests:

`2024-01-03 14:37:07,674 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
        at java.base/java.lang.String.charAt(String.java:1512)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.setIndexPage(StaticHandlerImpl.java:635)
        at io.quarkiverse.quinoa.QuinoaUIResourceHandler.createStaticHandler(QuinoaUIResourceHandler.java:67)
        at io.quarkiverse.quinoa.QuinoaUIResourceHandler.<init>(QuinoaUIResourceHandler.java:37)
        at io.quarkiverse.quinoa.QuinoaRecorder.quinoaHandler(QuinoaRecorder.java:41)
        at io.quarkus.deployment.steps.QuinoaProcessor$runtimeInit397778252.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.QuinoaProcessor$runtimeInit397778252.deploy(Unknown Source)
        ... 13 more`

### Package.json:
`
{
  "name": "lcm-webui",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "^18",
    "react-dom": "^18",
    "next": "14.0.4"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "eslint": "^8",
    "eslint-config-next": "14.0.4"
  }
}
`

### next.config.js
`const nextConfig = {
    output: 'export',
}
module.exports = nextConfig
`

### Quinoa version
2.3.1

### Quarkus version
3.6.4

### Build / Runtime
Next.js

### Package Manager
NPM

**Comment by melloware** [comment]
@shivam-sharma7 didn't you just work with a NextJS project?  I know I had it working last year with a NextJS project using NextJS 12.

**Comment by melloware** [comment]
@l2c0r3 can you put together a small reproducer using a simple nextjs app showing the issue?

**Comment by l2c0r3** [comment]
@melloware okay, I will do it tomorrow

**Comment by melloware** [comment]
Confirmed!  Here is the reproducer:

[nextjs-project.zip](https://github.com/quarkiverse/quarkus-quinoa/files/13822758/nextjs-project.zip)

I get the same error as you.

**Comment by l2c0r3** [comment]
With NextJS version 13.5.6 I have noticed the same thing: DEV mode works but the QuarkusIntegrationTests throws the same error as mentioned.

[web-ui.zip](https://github.com/quarkiverse/quarkus-quinoa/files/13829145/web-ui.zip)

**Comment by melloware** [comment]
@l2c0r3 found a workaround  Juts add this to your application.properties.

```
quarkus.quinoa.dev-server.index-page=/index.html
```

That makes the PROD mode work.

@ia3andy I htink there is something wrong with `NextFramework.java` and this block of code that is making the index empty `""` in PRD mode thus causing the Vert.X error above.

```java
        return new QuinoaConfigDelegate(super.override(delegate, packageJson, detectedDevScript, isCustomized)) {

            @Override
            public DevServerConfig devServer() {
                return new DevServerConfigDelegate(super.devServer()) {
                    @Override
                    public Optional<String> indexPage() {
                        // In Dev mode Next.js serves everything out of root "/" but in PRD mode it is the
                        // normal "/index.html".
                        return Optional.of(super.indexPage().orElse("/"));
                    }
                };
            }
        };
```

**Comment by l2c0r3** [comment]
Many thanks for the quick answers and analyse @melloware! 

Unfortunately, the workaround only works to a limited extent:
The QuarkusIntegrationTests are now running, but the DEV mode no longer works as expected: When I call localhost:8080 it responds now with a status code 404, and not with the nextjs page as before.

I have noticed this with my project as well as your reproducer.

**Comment by melloware** [comment]
Yep I was just trying to get your past your prd mode issue.  The real issue is a bug in `nextframework.java` overriding the static page to `""`.

**Comment by l2c0r3** [comment]
Ah I understand. Many thanks to you

**Comment by melloware** [comment]
Also created #606 which can use the same reproducer from this ticket.

**Comment by ia3andy** [comment]
Thanks for reporting this @l2c0r3, the error you've catched is just the tip of the iceberg as this could affect any production apps using the configured devserver index page name (instead of the prod one).

**To mitigate this issue, most of the time, the dev server index page name is the same as the prod one. Also the server would not start in production or the index won't be accessible (i.e. you would catch this really fast)**

**Comment by melloware** [comment]
@all-contributors add @l2c0r3 for bug
