### ISSUE TITLE
 Quarkus startup failure

### ISSUE THREAD

**Issue by fordsworth** [quarkiverse/quarkus-quinoa#704]
### Describe the bug

When  running quarkus dev for an app that uses Quarkus + angular  java.lang.NoClassDefFoundError: io/quarkus/vertx/http/deployment/spi/GeneratedStaticResourceBuildItem is thrown.

this works perfectly well on version 2.3.7 

❯ quarkus dev
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< org.acme:code-with-quarkus >---------------------
[INFO] Building code-with-quarkus 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus:3.11.3:dev (default-cli) @ code-with-quarkus ---
[INFO] Invoking resources:3.3.1:resources (default-resources) @ code-with-quarkus
[INFO] Copying 1 resource from src/main/resources to target/classes
[INFO] Invoking quarkus:3.11.3:generate-code (default) @ code-with-quarkus
[INFO] Invoking compiler:3.12.1:compile (default-compile) @ code-with-quarkus
[INFO] Nothing to compile - all classes are up to date.
[INFO] Invoking resources:3.3.1:testResources (default-testResources) @ code-with-quarkus
[INFO] skip non existing resourceDirectory /Users/litts/Downloads/code-with-quarkus 2/src/test/resources
[INFO] Invoking quarkus:3.11.3:generate-code-tests (default) @ code-with-quarkus
[INFO] Invoking compiler:3.12.1:testCompile (default-testCompile) @ code-with-quarkus
[INFO] Nothing to compile - all classes are up to date.
Listening for transport dt_socket at address: 5005
2024-06-24 09:30:14,030 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2024-06-24 09:30:14,241 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.NoClassDefFoundError: io/quarkus/vertx/http/deployment/spi/GeneratedStaticResourceBuildItem
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
        at java.base/java.lang.Class.forName(Class.java:513)
        at io.quarkus.deployment.util.ServiceUtil.classesNamedIn(ServiceUtil.java:29)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:160)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:327)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:58)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:113)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:435)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:56)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.ClassNotFoundException: io.quarkus.vertx.http.deployment.spi.GeneratedStaticResourceBuildItem
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:526)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:476)
        ... 16 more

### Quinoa version

2.4.0

### Quarkus version

3.11.3

### Build / Runtime

Angular

### Package Manager

NPM

### Steps to reproduce the behavior

1. new quarkus project 
2. new angular 18 project 
3. quarkus dev 

reference sample project 
https://github.com/fordsworth/quarkus-quinoa-2.4

**Comment by ia3andy** [comment]
Hello @fordsworth, you need to use Quarkus 3.12 with 2.4.0, see: https://github.com/quarkiverse/quarkus-quinoa?tab=readme-ov-file#versioning


@aloubyansky @maxandersen not having a way to set a compatibility flag in the code is really a big issue IMO

**Comment by fordsworth** [comment]
Thanks @ia3andy  noted
