### ISSUE TITLE
Quinoa does not find node or yarn executable on Windows

### ISSUE THREAD

**Issue by rmanibus** [quarkiverse/quarkus-quinoa#84]
Quinoa fail on windows complaining that it cannot find node or yarn executable (even if they are in path)
It can be reproduced with the starter code and maven or gradle.

I double check that the path is visible to java and contains yarn folder. The only thing I saw is that the env name on windows is lowercased ("Path"). I'm not sure how the ProcessBuilder resolve the binary path but it might be related to that.

```
<====2022-05-31 22:58:28,018 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.quinoa.deployment.ForwardedDevProcessor#prepareDevService threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Input/Output error while running process.
        at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Input/Output error while running process.
        at io.quarkiverse.quinoa.deployment.PackageManager.process(PackageManager.java:170)
        at io.quarkiverse.quinoa.deployment.PackageManager.dev(PackageManager.java:102)
        at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:120)
        ... 11 more
Caused by: java.io.IOException: Cannot run program "yarn" (in directory "C:\Users\loich\workspace\Projets\handyman\main-partition\..\webui"): CreateProcess error=2, Le fichier sp?cifi? est introuvable
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at io.quarkus.deployment.util.ProcessUtil.launchProcess(ProcessUtil.java:38)
        at io.quarkiverse.quinoa.deployment.PackageManager.process(PackageManager.java:168)
        ... 13 more
Caused by: java.io.IOException: CreateProcess error=2, Le fichier sp?cifi? est introuvable
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 16 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:95)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:485)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:68)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:142)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:97)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.quinoa.deployment.ForwardedDevProcessor#prepareDevService threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Input/Output error while running process.
        at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Input/Output error while running process.
        at io.quarkiverse.quinoa.deployment.PackageManager.process(PackageManager.java:170)
        at io.quarkiverse.quinoa.deployment.PackageManager.dev(PackageManager.java:102)
        at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:120)
        ... 11 more
Caused by: java.io.IOException: Cannot run program "yarn" (in directory "C:\Users\loich\workspace\Projets\handyman\main-partition\..\webui"): CreateProcess error=2, Le fichier sp?cifi? est introuvable
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at io.quarkus.deployment.util.ProcessUtil.launchProcess(ProcessUtil.java:38)
        at io.quarkiverse.quinoa.deployment.PackageManager.process(PackageManager.java:168)
        ... 13 more
Caused by: java.io.IOException: CreateProcess error=2, Le fichier sp?cifi? est introuvable
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 16 more

        at io.quarkus.builder.Execution.run(Execution.java:116)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:157)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328)
        ... 9 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Input/Output error while running process.
        at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Input/Output error while running process.
        at io.quarkiverse.quinoa.deployment.PackageManager.process(PackageManager.java:170)
        at io.quarkiverse.quinoa.deployment.PackageManager.dev(PackageManager.java:102)
        at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:120)
        ... 11 more
Caused by: java.io.IOException: Cannot run program "yarn" (in directory "C:\Users\loich\workspace\Projets\handyman\main-partition\..\webui"): CreateProcess error=2, Le fichier sp?cifi? est introuvable
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at io.quarkus.deployment.util.ProcessUtil.launchProcess(ProcessUtil.java:38)
        at io.quarkiverse.quinoa.deployment.PackageManager.process(PackageManager.java:168)
        ... 13 more
Caused by: java.io.IOException: CreateProcess error=2, Le fichier sp?cifi? est introuvable
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
```

**Comment by rmanibus** [comment]
Hello @ia3andy , I reopened the issue here. In the meantime I double checked that the path in java (System.getenv) contains yarn directory.
Also setting an absolute path in quinoa.package-manager does not seems to work (it's failing with the same error).

**Comment by rmanibus** [comment]
yes sorry I copied it from yaml and forgot the first line

**Comment by ia3andy** [comment]
@rmanibus I am not on Windows, would check how to run basic Java main which start a `yarn` or `npm` process using Java `ProcessBuilder`.

**Comment by ia3andy** [comment]
because in the end it's just a `ProcessBuilder` with `["yarn", "run", "build"]` as cmd

**Comment by rmanibus** [comment]
@ia3andy Well I just tried and it is failing. I cannot find anything about it in the doc but I guess that on windows executable path must be resolved manually from path env variable before being passed to the process builder

**Comment by ia3andy** [comment]
Yeah that's it: https://stackoverflow.com/questions/26992165/how-to-set-path-environment-variable-in-processbuilder-java-in-windows

@geoand maybe you know some code in Quarkus where we had a similar issue?

**Comment by ia3andy** [comment]
@rmanibus this also mean that absolute path should work in , could you try with `\` and also with `/` in `quarkus.quinoa.package-manager=...` to make sure we covered it all :)

**Comment by geoand** [comment]
We don't have any specific code handling PATH IIRC. Having a property where users set the full path of the binary (if necessary) is the way to go

**Comment by ia3andy** [comment]
@rmanibus it seems you need the path absolute with `\`, is it what you tried?

**Comment by ia3andy** [comment]
It seems @fblan managed to make it work on windows, did you have to do something special to have the PATH working?

**Comment by fblan** [comment]
Hi,I had a similar issue with npm : on windows the name of npm executable is npm.cmd, so to make it work with quinoa, I had to put in application.properties : quarkus.quinoa.package-manager=npm.cmd
I think for yarn you could try quarkus.quinoa.package-manager=yarn.cmd

**Comment by rmanibus** [comment]
That was indeed the problem. thank you @fblan ! @ia3andy maybe some logic can be added to support this without extra configuration ?

**Comment by ia3andy** [comment]
Yes for sure! I was just waiting for confirmation that it solved the problem :) Would one of you want to try to provide a PR?

**Comment by fblan** [comment]
I have submitted a pull request. Please don't hesitate to tell me if I did something wrong: https://github.com/quarkiverse/quarkus-quinoa/pull/93
